name: 'AWS Secrets Manager Action'
author: 'Abhilash Kishore'
description: 'Use secret from AWS Secrets Manager as environment variables in your GitHub Actions workflow'
inputs:
  secret_name:
    description: 'Secret name you want to import'
    required: true
  env_vars:
    description: 'Environmental variables to export'
    required: true
  disable-warnings:
    description: 'If true, disable annotation warnings in the GitHub Actions output.'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: lock
  color: blue
